version: "2"

services:
  build:
    image: git.mixedup.dev/refuel/docker-cross-compiler
    command: "/home/refuel/src/build_native.sh"
    volumes:
      - .:/home/refuel/src
  publish:
    image: git.mixedup.dev/refuel/docker-cross-compiler
    command: "/home/refuel/src/publish.sh"
    environment:
      QUIK_API_KEY: ${QUIK_API_KEY}
    volumes:
      - .:/home/refuel/src
      