name: Build
run-name: Building docker container.
on:
  workflow_dispatch:
  push:
    branches: stable

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      QUIK_API_KEY: "${{secrets.QUIK_API_KEY}}"
    steps:
      - name: Update Package Repository.
        run: apt update -y
      - name: Gather dependencies.
        run: apt install -y docker.io docker-compose
      - name: Check repository out.
        uses: actions/checkout@v3
      - name: "Where are my files????"
        run: ls -la
      - name: Run Build Script
        run: docker-compose run build
        working-directory: ${{ gitea.workspace }}
      - name: Upload NuGet Package
        run: "bash ${{ gitea.workspace }}/publish.sh"
