name: Build
run-name: Building docker container.
on:
  workflow_dispatch:
  push:
    branches: stable

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      QUIK_API_KEY: "${{secrets.QUIK_API_KEY}}"
    steps:
      - name: Update Package Repository.
        run: apt update -y
      - name: Gather dependencies.
        run: apt install -y docker.io docker-compose
      - name: Check repository out.
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Run Build Script
        run: "bash ${{ gitea.workspace }}/build_ci_cd.sh"
