name: Build
run-name: Building with docker container.
on:
  workflow_dispatch:
  tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: git.mixedup.dev/refuel/docker-cross-compiler
      env:
        QUIK_API_KEY: "${{secrets.REFUEL_API_KEY}}"
        NUGET_USER_NAME: "${{vars.NUGET_USER_NAME}}"
        NUGET_INDEX: "${{vars.NUGET_INDEX}}"
      volumes:
        - ${{ gitea.workspace }}:/home/refuel/src
    steps:
      - name: Check repository out.
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Run Build Script
        run: "./build_native.sh"
      - name: Publish Package
        run: "./publish.sh"
